# name: AI Code Review
# on:
#   pull_request:
#     types: [opened]

# permissions: write-all

# jobs:
#   review:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Run AI Code Review
#         uses: villesau/ai-codereviewer@main
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           openai-api-key: ${{ secrets.OPENAI_API_KEY }}
#           OPENAI_API_MODEL: "gpt-4"

