name: CI Workflow

on:
  push:
    branches: [main]
    branches-ignore: [test]

    paths-ignore:
      - 'docs/**'
      - 'tests/**'
      - '.github/workflows/ci.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building the project ..."