name: CI Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Installing dependencies ..."
          echo "status=success" >> $GITHUB_OUTPUT
        id: step1
      - name: Test
        run: |
          echo "El resultado del paso anterior fue ${{ steps.step1.outputs.status }}"
          echo "Running tests ..."
        id: step2